import type { IndustryTemplate } from "./commission-store";

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: "water",
    name: "Water Systems",
    description: "Residential water treatment / softeners with finance partner and install fee.",
    emoji: "💧",
    charges: [
      { label: "Install fee", amount: 350 },
      { label: "Permit", amount: 75 },
    ],
    finance: {
      name: "AquaFinance",
      defaultFee: 0.07,
      dealerFee: 195,
      adminFee: 50,
      usesApprovalDiscount: true,
      notes: "Standard dealer fee + 7% finance fee.",
    },
    tiers: [
      { minVolume: 0, rate: 0.1 },
      { minVolume: 10000, rate: 0.14 },
      { minVolume: 30000, rate: 0.18 },
    ],
    overrides: [
      { level: 1, rate: 0.05 },
      { level: 2, rate: 0.02 },
    ],
    taxReservePercent: 0.22,
  },
  {
    id: "solar",
    name: "Solar",
    description: "Residential solar with PPA/finance, redline pricing and dealer fee.",
    emoji: "☀️",
    charges: [{ label: "Engineering / permitting", amount: 500 }],
    finance: {
      name: "GoodLeap",
      defaultFee: 0.18,
      dealerFee: 0,
      adminFee: 0,
      usesApprovalDiscount: true,
      notes: "Dealer fee bundled into redline.",
    },
    tiers: [
      { minVolume: 0, rate: 0.05 },
      { minVolume: 20000, rate: 0.08 },
      { minVolume: 60000, rate: 0.12 },
    ],
    overrides: [
      { level: 1, rate: 0.03 },
      { level: 2, rate: 0.015 },
      { level: 3, rate: 0.01 },
    ],
    taxReservePercent: 0.25,
  },
  {
    id: "roofing",
    name: "Roofing",
    description: "Storm restoration and retail roofing with material + labor cost split.",
    emoji: "🏠",
    charges: [{ label: "Dump / disposal", amount: 350 }],
    finance: null,
    tiers: [
      { minVolume: 0, rate: 0.08 },
      { minVolume: 15000, rate: 0.12 },
      { minVolume: 50000, rate: 0.18 },
    ],
    overrides: [{ level: 1, rate: 0.04 }],
    taxReservePercent: 0.2,
  },
  {
    id: "hvac",
    name: "HVAC",
    description: "Residential HVAC replacement / install with finance and rebate credits.",
    emoji: "❄️",
    charges: [{ label: "Crane / lift", amount: 250 }],
    finance: {
      name: "Synchrony HVAC",
      defaultFee: 0.085,
      dealerFee: 125,
      adminFee: 0,
      usesApprovalDiscount: false,
      notes: "Promo finance program.",
    },
    tiers: [
      { minVolume: 0, rate: 0.08 },
      { minVolume: 10000, rate: 0.12 },
      { minVolume: 30000, rate: 0.16 },
    ],
    overrides: [
      { level: 1, rate: 0.04 },
      { level: 2, rate: 0.02 },
    ],
    taxReservePercent: 0.22,
  },
  {
    id: "alarm",
    name: "Alarm Systems",
    description: "Security & monitoring; multipliers, RMR-based payout.",
    emoji: "🔔",
    charges: [{ label: "Activation", amount: 99 }],
    finance: null,
    tiers: [
      { minVolume: 0, rate: 0.12 },
      { minVolume: 5000, rate: 0.18 },
      { minVolume: 15000, rate: 0.25 },
    ],
    overrides: [
      { level: 1, rate: 0.06 },
      { level: 2, rate: 0.03 },
      { level: 3, rate: 0.015 },
    ],
    taxReservePercent: 0.2,
  },
  {
    id: "home-improvement",
    name: "Home Improvement",
    description: "Windows, baths, siding — finance partner with redline pricing.",
    emoji: "🔨",
    charges: [{ label: "Measure / design", amount: 200 }],
    finance: {
      name: "Service Finance",
      defaultFee: 0.11,
      dealerFee: 150,
      adminFee: 25,
      usesApprovalDiscount: true,
      notes: "",
    },
    tiers: [
      { minVolume: 0, rate: 0.07 },
      { minVolume: 12000, rate: 0.11 },
      { minVolume: 40000, rate: 0.15 },
    ],
    overrides: [
      { level: 1, rate: 0.035 },
      { level: 2, rate: 0.015 },
    ],
    taxReservePercent: 0.22,
  },
  {
    id: "real-estate",
    name: "Real Estate Referrals",
    description: "Per-deal referral fees with simple flat overrides.",
    emoji: "🏡",
    charges: [],
    finance: null,
    tiers: [
      { minVolume: 0, rate: 0.25 },
      { minVolume: 25000, rate: 0.35 },
    ],
    overrides: [{ level: 1, rate: 0.1 }],
    taxReservePercent: 0.28,
  },
  {
    id: "life-insurance",
    name: "Life Insurance",
    description: "Term & whole life policies; commission based on annualized premium (AP) with carrier overrides.",
    emoji: "🛡️",
    charges: [
      { label: "Policy issue fee", amount: 50 },
      { label: "Underwriting / exam", amount: 75 },
    ],
    finance: {
      name: "Carrier (e.g. Mutual of Omaha)",
      defaultFee: 0,
      dealerFee: 0,
      adminFee: 25,
      usesApprovalDiscount: true,
      notes: "Commission paid as % of first-year annualized premium. Chargebacks apply if policy lapses in NTO period.",
    },
    tiers: [
      { minVolume: 0, rate: 0.5 },
      { minVolume: 25000, rate: 0.7 },
      { minVolume: 75000, rate: 0.9 },
    ],
    overrides: [
      { level: 1, rate: 0.1 },
      { level: 2, rate: 0.05 },
      { level: 3, rate: 0.025 },
    ],
    taxReservePercent: 0.25,
  },
  {
    id: "dealer",
    name: "Finance / Dealer Sales",
    description: "Indirect lending / dealer commission with admin & dealer fees.",
    emoji: "🚗",
    charges: [],
    finance: {
      name: "Generic Lender",
      defaultFee: 0.04,
      dealerFee: 295,
      adminFee: 75,
      usesApprovalDiscount: false,
      notes: "",
    },
    tiers: [
      { minVolume: 0, rate: 0.06 },
      { minVolume: 8000, rate: 0.09 },
      { minVolume: 25000, rate: 0.13 },
    ],
    overrides: [
      { level: 1, rate: 0.03 },
      { level: 2, rate: 0.015 },
    ],
    taxReservePercent: 0.22,
  },
];
